---
- name: Debian/Ubuntu Family | Add gpg signing keys
  become: yes
  apt_key:
    url: "{{ item.gpg_key }}"
    state: present
    keyring: "{{ item.gpg_keyring_file }}"
  with_items: "{{ apt_repos }}"

- name: Debian/Ubuntu Family | Adding apt repositories
  become: yes
  apt_repository:
    repo: "{{ item.repo_debian }}"
    state: "{{ item.repo_desired_state }}"
    filename: "{{ item.repo_debian_filename }}"
    update_cache: yes
  loop: "{{ apt_repos }}"

- name: Install apt packages
  become: true
  apt: 
    pkg: "{{ apt_installed_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  notify:
    - Restart network manager

# - include_role:
#     name: github-releases
#   with_items: "{{ github_releases }}"

- name: Install snap packages
  become: true
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
    channel: "{{ item.channel | default('stable') }}"
  with_items: "{{ snap_installed_packages }}"

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add current user to docker group
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_facts['env']['USERNAME'] }}"
    groups: docker
    append: yes

- include_role:
    name: "{{ item }}"
  loop:
    - linux
