---
- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts
  when: debug is defined

- import_tasks: MacOS.yml
  when: ansible_os_family == 'Darwin'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'


- include_role:
    name: "{{ item }}"
  loop:
    - jetbrains
    - shell
    - python
    - gnome
    - monitoring
