---
- hosts: localhost
  user: eanbar
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
