---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: cloudalchemy.prometheus
  - name: cloudalchemy.grafana
  - name: cloudalchemy.node_exporter
  - name: staticdev.pyenv

collections:
  - name: geerlingguy.mac
