---
- name: Get github releases
  uri:
    url: "https://api.github.com/repos/{{ item.repo }}/releases/latest"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result
  retries: 10
  delay: 30

- name: Get specific release version
  ansible.builtin.set_fact:
    version: "{{ result.json.tag_name }}"

- name: Download binary
  include_tasks: download-binary.yml
  when: item.type == "binary"

- name: Download archive
  include_tasks: download-archive.yml
  when: item.type != "binary"
