---
# tasks file for python
- name: Install global pip packages
  ansible.builtin.pip:
    virtualenv: "{{ python_virtual_env_python }}"
    name: "{{ python_virtual_env_pip_packages }}"
    state: present
